#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find /home/potato/workplace -mindepth 4 -maxdepth 4 -type d -path "*/src/*" \
        | awk -F '/src/' '{print $2 "("$1")"}' \
        | sed -E 's|/[^/]+||2g' \
        | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

package=$(echo "$selected" | sed -E 's|\((.*)\)||' | xargs)
project=$(echo "$selected" | grep -oP '(?<=\().*(?=\))')

full_path=$(find /home/potato/workplace -type d -path "*/$project/src/$package" | head -n 1)

if [[ -z $full_path ]]; then
    echo "Error: Could not resolve the full path for the selected package"
    exit 1
fi

cd "$full_path" || exit 1

exec $SHELL -l
